name = "StaticTaylorSeries"
uuid = "91725f60-9ab6-11e9-00d0-87fe6d51fd3a"
authors = ["David Sanders <dpsanders@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
